# Generated by Django 3.1.5 on 2021-10-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name_plural': 'Discussions'},
        ),
    ]
