# Generated by Django 3.1.5 on 2021-06-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20210606_1132'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsCollectiveMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.individualcollectivemission')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teamcommentsboard',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='teamcommentsboard',
            name='team',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentResponse',
        ),
        migrations.DeleteModel(
            name='CollectiveMissionComments',
        ),
        migrations.DeleteModel(
            name='TeamCommentsBoard',
        ),
        migrations.AddField(
            model_name='commentsteam',
            name='responses',
            field=models.ManyToManyField(to='message.CommentResponse'),
        ),
        migrations.AddField(
            model_name='commentsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.team'),
        ),
        migrations.AddField(
            model_name='commentsteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentscollectivemission',
            name='team_comments',
            field=models.ManyToManyField(to='message.CommentsTeam'),
        ),
    ]
