# Generated by Django 3.1.5 on 2021-04-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210426_1305'),
        ('message', '0002_auto_20210428_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionComments',
            new_name='CollectiveMissionComments',
        ),
    ]
