# Generated by Django 3.1.5 on 2021-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211015_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('w_r', 'Waiting review'), ('u_r', 'Under Review'), ('a', 'Accepted'), ('r', 'To Review'), ('c', 'See Comments')], default='w_r', max_length=20),
        ),
    ]
