# Generated by Django 3.1.5 on 2021-06-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20210607_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('comment_text', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentscollectivemission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='commentscollectivemission',
            name='team_comments',
        ),
        migrations.RemoveField(
            model_name='commentsteam',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='commentsteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='commentsteam',
            name='user',
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.comment')),
                ('title', models.CharField(max_length=50)),
            ],
            bases=('message.comment',),
        ),
        migrations.DeleteModel(
            name='CommentResponse',
        ),
        migrations.DeleteModel(
            name='CommentsCollectiveMission',
        ),
        migrations.DeleteModel(
            name='CommentsTeam',
        ),
    ]
