# Generated by Django 3.1.5 on 2021-11-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20211104_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
