dir=[['DoesNotExist', 'Meta', 'MultipleObjectsReturned', 'RESPONSE_TYPE', 'STAGE_CHOICE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_check_column_name_clashes', '_check_constraints', '_check_field_name_clashes', '_check_fields', '_check_id_field', '_check_index_together', '_check_indexes', '_check_local_fields', '_check_long_column_names', '_check_m2m_through_same_relationship', '_check_managers', '_check_model', '_check_model_name_db_lookup_clashes', '_check_ordering', '_check_property_name_related_field_accessor_clashes', '_check_single_primary_key', '_check_swappable', '_check_unique_together', '_do_insert', '_do_update', '_get_FIELD_display', '_get_next_or_previous_by_FIELD', '_get_next_or_previous_in_order', '_get_pk_val', '_get_unique_checks', '_meta', '_perform_date_checks', '_perform_unique_checks', '_save_parents', '_save_table', '_set_pk_val', '_state', 'acquired_skill', 'answer', 'answer_form', 'attributed_to', 'attributed_to_id', 'check', 'clean', 'clean_fields', 'created_date', 'date_error_message', 'delete', 'description', 'discussion_form', 'discussions', 'due_date', 'field', 'field_id', 'from_db', 'full_clean', 'get_absolute_url', 'get_deferred_fields', 'get_next_by_created_date', 'get_next_by_due_date', 'get_previous_by_created_date', 'get_previous_by_due_date', 'get_response_type_display', 'get_stage_display', 'get_update_url', 'hard_skill_rating', 'id', 'level', 'level_id', 'name', 'objects', 'owner', 'owner_id', 'pk', 'points', 'prepare_database_save', 'project', 'project_id', 'refresh_from_db', 'resources', 'response_type', 'save', 'save_base', 'serializable_value', 'stage', 'unique_error_message', 'validate_unique']
]
dir_answer =['_constructor_args', 'creation_counter', 'model', 'name', '_db', '_hints', 'instance', 'get_content_type', 'content_type', 'content_type_field_name', 'object_id_field_name', 'prefetch_cache_name', 'pk_val', 'core_filters', '__module__', '__init__', '__call__', 'do_not_call_in_templates', '__str__', '_apply_rel_filters', '_remove_prefetched_objects', 'get_queryset', 'get_prefetch_queryset', 'add', 'remove', 'clear', '_clear', 'set', 'create', 'get_or_create', 'update_or_create', '__doc__', '__slotnames__', '_queryset_class', '_insert', '_update', 'aggregate', 'annotate', 'bulk_create', 'bulk_update', 'complex_filter', 'count', 'dates', 'datetimes', 'defer', 'difference', 'distinct', 'earliest', 'exclude', 'exists', 'explain', 'extra', 'filter', 'first', 'get', 'in_bulk', 'intersection', 'iterator', 'last', 'latest', 'none', 'only', 'order_by', 'prefetch_related', 'raw', 'reverse', 'select_for_update', 'select_related', 'union', 'update', 'using', 'values', 'values_list', 'auto_created', 'use_in_migrations', '__new__', '__class_getitem__', 'deconstruct', 'check', '_get_queryset_methods', 'from_queryset', 'contribute_to_class', '_set_creation_counter', 'db_manager', 'db', 'all', '__eq__', '__hash__', '__dict__', '__weakref__', '__repr__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', '__le__', '__ne__', '__gt__', '__ge__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']
def get_dir(dir):
    for name in dir:
        print(name)



get_dir(dir)
