# Generated by Django 3.1.5 on 2021-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210701_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='join_code',
            field=models.CharField(default=123456789, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
