# Generated by Django 3.1.5 on 2021-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210603_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/avatar.png', null=True, upload_to='media/profile/'),
        ),
    ]
