# Generated by Django 3.1.5 on 2021-06-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210607_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='email',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='phone_number',
        ),
    ]
