# Generated by Django 3.1.5 on 2021-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210608_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
    ]
