# Generated by Django 3.1.5 on 2021-03-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('team_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='content.team')),
            ],
        ),
    ]
