# Generated by Django 3.1.5 on 2021-04-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_1104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='entered_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='personaltask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='personaltask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.myuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentTeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('team_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.teamtask')),
            ],
        ),
        migrations.AddField(
            model_name='teamtask',
            name='assignees',
            field=models.ManyToManyField(blank=True, through='todo.StudentTeamTask', to='accounts.Student'),
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.task')),
                ('completed', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            bases=('todo.task',),
        ),
    ]
