<<<<<<< HEAD:accounts/migrations/0003_auto_20210512_1130.py
# Generated by Django 3.1.5 on 2021-05-12 11:30
=======
# Generated by Django 3.1.5 on 2021-05-12 08:28
>>>>>>> 8998654a0a4f23616f19f42fb17a6c518b846f99:accounts/migrations/0002_auto_20210512_0828.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0002_auto_20210512_0828'),
        ('content', '0001_initial'),
<<<<<<< HEAD:accounts/migrations/0003_auto_20210512_1130.py
        ('backend', '0002_auto_20210512_1130'),
        ('accounts', '0002_auto_20210512_1130'),
        ('auth', '0012_alter_user_first_name_max_length'),
=======
        ('accounts', '0001_initial'),
>>>>>>> 8998654a0a4f23616f19f42fb17a6c518b846f99:accounts/migrations/0002_auto_20210512_0828.py
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='softs_skills',
            field=models.ManyToManyField(related_name='student_skills_scores', through='backend.StudentSoftSkillRating', to='content.Skills'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speaker',
            name='group',
            field=models.ManyToManyField(to='backend.Group'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='institution',
            field=models.ManyToManyField(to='backend.Institution'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
