# Generated by Django 3.1.5 on 2021-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210310_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('he', 'Hebrew')], default='en', max_length=50),
        ),
    ]
