# Generated by Django 3.1.5 on 2021-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210701_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
