# Generated by Django 3.1.5 on 2021-04-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_teacher',
            new_name='is_speaker',
        ),
    ]
