# Generated by Django 3.1.5 on 2021-08-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210808_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field',
        ),
    ]
