# Generated by Django 3.1.5 on 2021-10-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210826_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=50, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
