# Generated by Django 3.1.5 on 2021-04-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', 'Start'), ('middle', 'Middle'), ('final', 'Final')], default='start', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('response_comment', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', 'Start'), ('middle', 'Middle'), ('final', 'Final')], default='start', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('response_comment', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='')),
                ('accepted', models.BooleanField(default=False)),
                ('attributed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_missions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('s_m', 'Student Mission'), ('t_m', 'Team Mission')], default='s_m', max_length=200)),
                ('response_type', models.CharField(choices=[('link', 'Link'), ('video', 'Video'), ('doc', 'Document'), ('power_p', 'Power Point'), ('image', 'image')], default=None, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('time_to_complet', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('project_completed', models.BooleanField(blank=True, null=True)),
                ('group_Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
                ('individaul_missions', models.ManyToManyField(through='content.IndividualProjectMission', to='content.Mission')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to='accounts.speaker')),
                ('participants', models.ManyToManyField(blank=True, to='accounts.Student')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
                ('team_missions', models.ManyToManyField(related_name='team_missions', through='content.CollectiveProjectMission', to='content.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_acquired', models.BooleanField(default=False)),
                ('field', models.ManyToManyField(to='backend.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(default='image/default.png', upload_to='images/')),
                ('file_rsc', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.TextField()),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.field')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='acquried_skills',
            field=models.ManyToManyField(to='content.Skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.level'),
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.ManyToManyField(to='backend.Field'),
        ),
        migrations.AddField(
            model_name='project',
            name='missions',
            field=models.ManyToManyField(blank=True, to='content.Mission'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_skills', to='content.Skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.speaker'),
        ),
        migrations.AddField(
            model_name='mission',
            name='acquried_skill',
            field=models.ManyToManyField(blank=True, to='content.Skills'),
        ),
        migrations.AddField(
            model_name='mission',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.field'),
        ),
        migrations.AddField(
            model_name='mission',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.level'),
        ),
        migrations.AddField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='resources',
            field=models.ManyToManyField(to='content.Resource'),
        ),
        migrations.AddField(
            model_name='individualprojectmission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mission'),
        ),
        migrations.AddField(
            model_name='individualprojectmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.team'),
        ),
        migrations.CreateModel(
            name='IndividualCollectiveProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('response_comment', models.TextField(blank=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='')),
                ('accepted', models.BooleanField(default=False)),
                ('attributed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_team_mission', to='accounts.student')),
                ('parent_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.collectiveprojectmission')),
            ],
        ),
        migrations.AddField(
            model_name='collectiveprojectmission',
            name='attributed_to',
            field=models.ManyToManyField(blank=True, related_name='my_team_missions', through='content.IndividualCollectiveProjectMission', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='collectiveprojectmission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mission'),
        ),
        migrations.AddField(
            model_name='collectiveprojectmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.team'),
        ),
    ]
