# Generated by Django 3.1.5 on 2021-04-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='is_acquired',
        ),
    ]
