# Generated by Django 3.1.5 on 2021-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='aquried_skils',
        ),
        migrations.AddField(
            model_name='project',
            name='aquried_skils',
            field=models.ManyToManyField(to='content.SkillsAquired'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(to='content.RequiredSkills'),
        ),
    ]
