# Generated by Django 3.1.5 on 2021-07-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20210701_0919'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectivemission',
            name='acquired_skill',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='field',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='points',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='response_type',
        ),
        migrations.RemoveField(
            model_name='collectivemission',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='acquired_skill',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='field',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='points',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='response_type',
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='stage',
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', 'Start'), ('middle', 'Middle'), ('final', 'Final')], default='start', max_length=10)),
                ('response_type', models.CharField(choices=[('link', 'Link'), ('video', 'Video'), ('doc', 'Document'), ('power_p', 'Power Point'), ('image', 'image')], default=None, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('mission_type', models.CharField(choices=[('i', 'individual_mission'), ('c', 'collective_mission'), ('ci', 'collective_Individual_mission')], max_length=5)),
                ('acquired_skill', models.ManyToManyField(blank=True, to='content.Skills')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.field')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
                ('resources', models.ManyToManyField(blank=True, to='content.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectivemission',
            name='mission_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualmission',
            name='mission_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.mission'),
            preserve_default=False,
        ),
    ]
