# Generated by Django 3.1.5 on 2021-05-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='acquired_skill',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='field',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='points',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='response_type',
        ),
        migrations.RemoveField(
            model_name='individualcollectivemission',
            name='stage',
        ),
    ]
