# Generated by Django 3.1.5 on 2021-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='resources/default.png', upload_to='resources'),
        ),
    ]
