# Generated by Django 3.1.5 on 2021-04-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210413_1513'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='IndividualProjectMission',
            name='attributed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_missions', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_missions',
            field=models.ManyToManyField(through='content.IndividualProjectMission', to='content.Mission'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_missions',
            field=models.ManyToManyField(related_name='team_missions', through='content.CollectiveProjectMission', to='content.Mission'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_student_missions',
            field=models.ManyToManyField(related_name='team_student_missions', through='content.TeamCollectiveMission', to='content.Mission'),
        ),
        migrations.AlterField(
            model_name='teamcollectivemission',
            name='attributed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_mission', to='accounts.student'),
        ),
        migrations.RemoveField(
            model_name='CollectiveProjectMission',
            name='attributed_to',
        ),
        migrations.AddField(
            model_name='CollectiveProjectMission',
            name='attributed_to',
            field=models.ManyToManyField(blank=True, related_name='my_team_missions', to='accounts.Student'),
        ),
    ]
