# Generated by Django 3.1.5 on 2021-07-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210709_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.project'),
            preserve_default=False,
        ),
    ]
