# Generated by Django 3.1.5 on 2021-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210414_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='student_missions',
            new_name='individaul_missions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_student_missions',
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('s_m', 'Student Mission'), ('t_m', 'Team Mission')], default='s_m', max_length=200),
        ),
        migrations.DeleteModel(
            name='TeamCollectiveMission',
        ),
    ]
