# Generated by Django 3.1.5 on 2021-04-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_skills_is_acquired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='individaul_missions',
            new_name='individual_missions',
        ),
    ]
