# Generated by Django 3.1.5 on 2021-03-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210310_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprojectmission',
            name='mission_project',
        ),
        migrations.AddField(
            model_name='team',
            name='missions',
            field=models.ManyToManyField(through='content.TeamProjectMission', to='content.Mission'),
        ),
        migrations.AddField(
            model_name='teamprojectmission',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.mission'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MissionsProject',
        ),
    ]
