# Generated by Django 3.1.5 on 2021-05-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210426_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkillsRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('s_m', 'Individual Mission'), ('t_m', 'Collective Mission')], default='s_m', max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hard_skills', models.ManyToManyField(blank=True, through='content.HardSkillsRating', to='content.Skills')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
            ],
        ),
        migrations.AddField(
            model_name='hardskillsrating',
            name='project_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.projectmission'),
        ),
        migrations.AddField(
            model_name='hardskillsrating',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='missions',
            field=models.ManyToManyField(blank=True, through='content.ProjectMission', to='content.Mission'),
        ),
    ]
