# Generated by Django 3.1.5 on 2021-08-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210819_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.mission'),
        ),
    ]
