# Generated by Django 3.1.5 on 2021-03-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210310_1853'),
        ('content', '0003_auto_20210310_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aquried_skils',
            field=models.ManyToManyField(blank=True, to='content.SkillsAquired'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='content.RequiredSkills'),
        ),
        migrations.AlterField(
            model_name='team',
            name='final_project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(blank=True, to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='teamprojectmission',
            name='attributed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_mission', to='accounts.student'),
        ),
    ]
