# Generated by Django 3.1.5 on 2021-05-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210530_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectivemission',
            name='resources',
        ),
        migrations.AddField(
            model_name='collectivemission',
            name='resources',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.resource'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='individualmission',
            name='resources',
        ),
        migrations.AddField(
            model_name='individualmission',
            name='resources',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.resource'),
            preserve_default=False,
        ),
    ]
