# Generated by Django 3.1.5 on 2021-03-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210310_1853'),
        ('content', '0004_auto_20210313_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprojectmission',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teamprojectmission',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamprojectmission',
            name='attributed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_missions', to='accounts.student'),
        ),
    ]
