# Generated by Django 3.1.5 on 2021-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210317_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprojectmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
