# Generated by Django 3.1.5 on 2021-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210822_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='acquired_skills',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project/default_project.png', null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='resources/default.png', upload_to='resources/'),
        ),
    ]
