# Generated by Django 3.1.5 on 2021-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teamprojectmission_accepted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsAquired',
            new_name='SkillsAcquired',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aquried_skils',
        ),
        migrations.AddField(
            model_name='project',
            name='acquried_skils',
            field=models.ManyToManyField(blank=True, to='content.SkillsAcquired'),
        ),
    ]
