# Generated by Django 3.1.5 on 2021-10-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210826_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_rsc',
            field=models.FileField(blank=True, default='static/file.png', null=True, upload_to='resources/'),
        ),
    ]
