# Generated by Django 3.1.5 on 2021-03-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210318_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='final_project',
        ),
    ]
