# Generated by Django 3.1.5 on 2021-10-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20211015_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='group_Institution',
            new_name='group_institution',
        ),
    ]
