# Generated by Django 3.1.5 on 2021-11-04 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20211017_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
