# Generated by Django 3.1.5 on 2021-03-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_team_final_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
